services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: password  # 루트 비밀번호
      MYSQL_DATABASE: mydb               # 사용할 데이터베이스 이름
      MYSQL_USER: user                  # 일반 사용자
      MYSQL_PASSWORD: password          # 일반 사용자 비밀번호
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my-network

  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"  # Redis 기본 포트 매핑
    volumes:
      - redis-data:/data  # Redis 데이터 지속성 유지
    networks:
      - my-network
    restart: no

volumes:
  mysql_data:
  redis-data:

networks:
  my-network: